---
variables:
  QP_IMAGE_VERSION: "1.1.50"

include:
  - project: 'kxdev/shared-tools/ci-templates'
    ref: main
    file:
      - 'insights/qpacker.yaml'
      - 'insights/qbuild.yaml'
      - 'security/security.yaml'

default:
  tags:
    - kxi-gitlab-runner

stages:
  - build
  - scan
  - test
  - deploy

.default-rules:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_MERGE_REQUEST_IID

build-qpk:
  stage: build
  extends: .qpacker-build
  rules:
    - !reference [.default-rules, rules]
  variables:
    QPDOCKER_BUILD_BASE: "rockylinux/rockylinux:8"

release-libs:
  stage: deploy
  extends: .qpacker-push-qpks
